// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8p7Ju58I0eAfJ3GA8knRMC-h_zyMRuGw',
    appId: '1:922502154026:web:d7e5a5d7efe890a8cfc053',
    messagingSenderId: '922502154026',
    projectId: 'code-for-mr-toad',
    authDomain: 'code-for-mr-toad.firebaseapp.com',
    databaseURL: 'https://code-for-mr-toad-default-rtdb.firebaseio.com',
    storageBucket: 'code-for-mr-toad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ10qrN5_xLnV4T9qVVW-N3fSgINWjIKU',
    appId: '1:922502154026:android:e6134f5ba093b273cfc053',
    messagingSenderId: '922502154026',
    projectId: 'code-for-mr-toad',
    databaseURL: 'https://code-for-mr-toad-default-rtdb.firebaseio.com',
    storageBucket: 'code-for-mr-toad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGqbXo8t0iaGl4qmO4XdUmjFrXdwfeZBs',
    appId: '1:922502154026:ios:e45b5750ec59cc26cfc053',
    messagingSenderId: '922502154026',
    projectId: 'code-for-mr-toad',
    databaseURL: 'https://code-for-mr-toad-default-rtdb.firebaseio.com',
    storageBucket: 'code-for-mr-toad.appspot.com',
    iosClientId: '922502154026-co8ivv2ej2lqqlv9tak3gbcvtij8olco.apps.googleusercontent.com',
    iosBundleId: 'com.example.codetoad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGqbXo8t0iaGl4qmO4XdUmjFrXdwfeZBs',
    appId: '1:922502154026:ios:e45b5750ec59cc26cfc053',
    messagingSenderId: '922502154026',
    projectId: 'code-for-mr-toad',
    databaseURL: 'https://code-for-mr-toad-default-rtdb.firebaseio.com',
    storageBucket: 'code-for-mr-toad.appspot.com',
    iosClientId: '922502154026-co8ivv2ej2lqqlv9tak3gbcvtij8olco.apps.googleusercontent.com',
    iosBundleId: 'com.example.codetoad',
  );
}
