// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsa9e3Rvc1DEscPUp_KmLtOSRJE6wkuME',
    appId: '1:36772563161:web:a2db54dd85e3ae622a16c8',
    messagingSenderId: '36772563161',
    projectId: 'mr-toad-caf7c',
    authDomain: 'mr-toad-caf7c.firebaseapp.com',
    databaseURL: 'https://mr-toad-caf7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mr-toad-caf7c.appspot.com',
    measurementId: 'G-60WMWB2YTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ3ypd_ht9PML-wzLebyfqT8Z4wwzkiBQ',
    appId: '1:36772563161:android:5ac49e20c50334d02a16c8',
    messagingSenderId: '36772563161',
    projectId: 'mr-toad-caf7c',
    databaseURL: 'https://mr-toad-caf7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mr-toad-caf7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57gsye6bWVSlq1KE1NHkENQvzp_X3bns',
    appId: '1:36772563161:ios:0caa3e837f8999c42a16c8',
    messagingSenderId: '36772563161',
    projectId: 'mr-toad-caf7c',
    databaseURL: 'https://mr-toad-caf7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mr-toad-caf7c.appspot.com',
    iosClientId: '36772563161-918lqmurcpgrg4uuunlv0oepibnpf5bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.codetoad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57gsye6bWVSlq1KE1NHkENQvzp_X3bns',
    appId: '1:36772563161:ios:0caa3e837f8999c42a16c8',
    messagingSenderId: '36772563161',
    projectId: 'mr-toad-caf7c',
    databaseURL: 'https://mr-toad-caf7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mr-toad-caf7c.appspot.com',
    iosClientId: '36772563161-918lqmurcpgrg4uuunlv0oepibnpf5bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.codetoad',
  );
}
